version: "3.10"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver
    volumes:
      - .:/usr/src/app/NewsPaper
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A NewsPaper worker -l INFO
    volumes:
      - .:/usr/src/app/NewsPaper
    depends_on:
      - django
      - redis
  redis:
    image: "redis:alpine"
